input                  :  "/home/FCAM/hschober/methyl_pipeline/MethylForge/qc-nf/samplesheet.csv"
outdir                 :  "/home/FCAM/hschober/methyl_pipeline/MethylForge/test_output"
pore_type              :  "r10.4.1"
chemistry_type         :  "e8.2"
translocation_speed    :  "400bps"
model_version          :  "v5.0.0"
modification_name      :  "5mCG_5hmCG"
modification_version   :  "v3"
model_type             :  "sup"

